### ISSUE TITLE
Make non-case-sensitive

### ISSUE THREAD

**Issue by hhaslam11** [Joelio12/Alzheimers-Text-Based-Adventure-Game#2]
For example, typing "candlestick" in the inventory wont work, you need to type "Candlestick".
This could be fixed easily by comparing it using something like this: `if(toUpperCase(userInput).equals(toUpperCase(invItemName)){}`
_I didn't look at your code to much, so the variable probably will differ for you, but logic should remain the same_

This will result in Java comparing the two strings in their all caps form, so even if the user types `CaNdLe StIcK`, java will compare it as `CANDLE STICK`

It would be a lot more User Friendly IMO, and super easy to implement.

**Comment by Joel-Valentine** [comment]
Hey man, i'm currently just implementing features like enemies, friendlies, items, different types of items.. I haven't actually been creating any story elements just testing everything so the locations of all entities in rooms is very much just for testing, soon i will be creating a story for the game
thanks for attempting to play much appreciated, check back on the 31st.. Im hoping to have a story by then :D

**Comment by Joel-Valentine** [comment]
However the way i fixed the issue you are talking about is by making the user input go to lower case `setInput(sc.nextLine().toLowerCase())` and then having all the setters for entities be in lower case.. kind of hacky but works

**Comment by hhaslam11** [comment]
Yeah, basically what I suggested but lower case instead of upper case. Also, I think I had syntax errors in my method, get confused when switching languages.

**Comment by Joel-Valentine** [comment]
Yeah thanks for the issue report though! come back on the 31st. Should be in a playable state
